#!/usr/bin/env Rscript


library(tidyverse)


# Two-sided 95% confidence interval in terms of SEMs.
# Computed with integrals and stuff.
Z95 = 1.96


# Problem 1
# A group of 50 arts students and a group of 50 physics students underwent IQ testing.
# The code below generates the scores for both groups.
set.seed(1)
arts <- rnorm(n=50, mean=100, sd=15)
set.seed(31)  # Douglas Adams disapproves
physics <- rnorm(n=50, mean=100, sd=15)

# a. Calculate the 95% confidence intervals for the arts students.
one.a <- function(sample)
{
    # Returns the two-sided 95% confidence interval of the observed population.
    SD = sqrt(15)  # usually we don't know this
    SEM = SD / sqrt(length(sample))
    m = mean(sample)  # don't shadow mean() by declaring a variable with it's name

    c(m + SEM*Z95, m - SEM*Z95)
}
'1.a. 95% confidence interval'
one.a(arts)
''

# b. Does the observed mean of the physics students fall within the 95% confidence
# interval of the arts students?
'1.b. mean(physics) in interval(arts)'
local(
{
    interval <- one.a(arts)
    m <- mean(physics)

    ifelse(m < max(interval) && m > min(interval), 'yes', 'no')  # is the interval inclusive?
})
''

# c. What could we conclude based on this result?
'1.c. conclusion?'
'Based on the given data we are 95% confident that'
'the two samples are drawn from different generating distributions.'
# Embarrassingly, we know they are not.
''


# Problem 2
set.seed(31)
n <- 50
tibble(iq=rnorm(n*100, 100, 15), expt=rep(1:100, each=n)) %>%
    group_by(expt) %>%
    summarize(m = mean(iq), sdev = sd(iq), stderr = sdev /sqrt(n())) -> results

# a. Plot confidence intervals to see significant observations.
#ggplot(data = , mapping = aes()) + geom_point() + ggtitle('100 simulated IQ experiment with N=50')

# Graph is saved as './Rplots.pdf'.
results <- mutate(results, lower = m - stderr*Z95, upper = m + stderr*Z95)
ggplot(data=results, mapping=aes(x=expt, y=m)) +
    ggtitle('100 simulated IQ experiment with N=50') +
    xlab('Experiment') +
    ylab('Mean IQ') +
    geom_point() +
    geom_errorbar(mapping=aes(ymin=lower, ymax=upper)) +
    geom_hline(yintercept=100, colour="red")
